apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name:  redis
    app: app-votacion
spec:
  type: ClusterIP
  ports:
  - name:  "redis-service"
    port:  6379
    targetPort: 6379
  selector:
    name:  redis
    app: app-votacion