apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name:  db
    app: app-votacion
spec:
  type: ClusterIP
  ports:
  - name:  "db-service"
    port:  5432
    targetPort: 5432
  selector:
    name:  db
    app: app-votacion